apiVersion: v2
name: gatekeeper
description: Gatekeeper is a proxy which integrates with OpenID Connect (OIDC) Providers, it supports both access tokens in a browser cookie or bearer tokens.
type: application
home: https://github.com/gogatekeeper/helm-gogatekeeper
icon: https://gogatekeeper.github.io/logo/logo.svg
keywords:
  - gogatekeeper
  - gatekeeper
  - louketo
  - keycloak-gatekeeper
  - openid-connect
  - openid connect
  - oidc
  - proxy
  - access-proxy
  - reverse-proxy
  - authentication
  - authorization
  - sso
sources:
  - https://github.com/gogatekeeper/helm-gogatekeeper
  - https://gogatekeeper.github.io/
maintainers:
  - name: gogatekeeper
    url: https://gogatekeeper.github.io/
version: 0.1.28
appVersion: "2.0.0"
